import type { Brand, Category, Product, Testimonial } from "./types";

export const categories: Category[] = [
  { id: "dog", label: "Dog", count: 284 },
  { id: "cat", label: "Cat", count: 196 },
  { id: "treats", label: "Treats", count: 112 },
  { id: "vet", label: "Vet Care", count: 74 },
  { id: "toys", label: "Toys", count: 88 },
  { id: "home", label: "Home", count: 63 },
];

export const brands: Brand[] = [
  { id: "meadow", name: "Meadowkind", tag: "Grass-fed, slow cooked" },
  { id: "kinder", name: "Kinderbowl", tag: "Vet-formulated" },
  { id: "paw", name: "Pawpantry", tag: "Small-batch treats" },
  { id: "nestle", name: "Nestwell", tag: "Home & bedding" },
  { id: "pip", name: "Pip & Parsley", tag: "Functional supplements" },
];

export const products: Product[] = [
  {
    id: "p1",
    name: "Slow-Cooked Chicken & Oat",
    brand: "Meadowkind",
    pet: "dog",
    category: "Fresh food",
    price: 1480,
    unit: "2.5kg pouch",
    rating: 4.9,
    reviews: 1284,
    tags: ["Grain-friendly", "Adult", "Sensitive tummy"],
    blurb: "Gently cooked at 90°C so nutrients stay where they belong — in the bowl.",
    ingredients: [
      "Free-range chicken 62%",
      "Rolled oats",
      "Carrot & turmeric",
      "Flaxseed",
      "Salmon oil",
    ],
    tint: "#E8DCD5",
    shape: "pouch",
  },
  {
    id: "p2",
    name: "Ocean Whitefish Pâté",
    brand: "Kinderbowl",
    pet: "cat",
    category: "Wet food",
    price: 980,
    unit: "12 × 85g tins",
    rating: 4.8,
    reviews: 842,
    tags: ["Hairball support", "All ages", "High protein"],
    blurb: "Wild-caught whitefish whipped into a silky pâté cats actually come running for.",
    ingredients: ["Whitefish 74%", "Sweet potato", "Pumpkin", "Taurine", "Kelp"],
    tint: "#CFE3D8",
    shape: "tin",
  },
  {
    id: "p3",
    name: "Pumpkin & Peanut Biscuits",
    brand: "Pawpantry",
    pet: "dog",
    category: "Treats",
    price: 520,
    unit: "220g jar",
    rating: 4.9,
    reviews: 2104,
    tags: ["Grain-free", "Training", "Under 5 cal"],
    blurb: "Crunchy little rewards baked in a tiny bakery in Jabalpur. No nonsense.",
    ingredients: ["Pumpkin 38%", "Peanut butter", "Oat flour", "Honey", "Cinnamon"],
    tint: "#E8DCD5",
    shape: "jar",
  },
  {
    id: "p4",
    name: "Calming Chamomile Chews",
    brand: "Pip & Parsley",
    pet: "dog",
    category: "Supplements",
    price: 860,
    unit: "60 soft chews",
    rating: 4.7,
    reviews: 592,
    tags: ["Calming", "Travel", "Anxiety support"],
    blurb: "For fireworks, thunder, and the vacuum cleaner. Vet-approved botanicals.",
    ingredients: ["Chamomile extract", "L-theanine", "Valerian root", "Ginger"],
    tint: "#CFE3D8",
    shape: "jar",
  },
  {
    id: "p5",
    name: "Hempwood Crinkle Lounger",
    brand: "Nestwell",
    pet: "cat",
    category: "Home",
    price: 2480,
    unit: "One size — 52cm",
    rating: 4.8,
    reviews: 318,
    tags: ["Recycled", "Machine washable"],
    blurb: "A crinkle-lined nest that catches the afternoon sun beautifully.",
    ingredients: ["Recycled hemp fibre", "Organic cotton shell", "Crinkle liner"],
    tint: "#E8DCD5",
    shape: "bed",
  },
  {
    id: "p6",
    name: "River Salmon & Sweet Potato",
    brand: "Meadowkind",
    pet: "dog",
    category: "Fresh food",
    price: 1640,
    unit: "2.5kg pouch",
    rating: 4.9,
    reviews: 974,
    tags: ["Grain-free", "Omega-rich", "Sensitive skin"],
    blurb: "For the dog whose coat deserves a bit more shine.",
    ingredients: ["Rohu salmon 58%", "Sweet potato", "Peas", "Fish oil", "Seaweed"],
    tint: "#CFE3D8",
    shape: "pouch",
  },
  {
    id: "p7",
    name: "Felt Mouse Trio",
    brand: "Pawpantry",
    pet: "cat",
    category: "Toys",
    price: 640,
    unit: "Set of 3",
    rating: 4.6,
    reviews: 441,
    tags: ["Wool", "Catnip-filled", "Handmade"],
    blurb: "Three hand-felted mice, filled with organic catnip. Chaos guaranteed.",
    ingredients: ["Himalayan wool felt", "Organic catnip", "Cotton thread"],
    tint: "#E8DCD5",
    shape: "toy",
  },
  {
    id: "p8",
    name: "Dental Kelp Sticks",
    brand: "Pip & Parsley",
    pet: "dog",
    category: "Treats",
    price: 580,
    unit: "12 sticks",
    rating: 4.8,
    reviews: 712,
    tags: ["Dental", "Plaque support", "Daily"],
    blurb: "One a day keeps the tartar away. Mildly minty, wildly effective.",
    ingredients: ["Kelp 28%", "Parsley", "Tapioca", "Peppermint oil"],
    tint: "#CFE3D8",
    shape: "stick",
  },
  {
    id: "p9",
    name: "Gentle Paw Balm",
    brand: "Pip & Parsley",
    pet: "dog",
    category: "Vet Care",
    price: 780,
    unit: "50ml tin",
    rating: 4.9,
    reviews: 388,
    tags: ["Balm", "Winter", "Natural"],
    blurb: "Shea and calendula for paws that have seen a few adventures.",
    ingredients: ["Shea butter", "Calendula", "Beeswax", "Vitamin E"],
    tint: "#E8DCD5",
    shape: "tin",
  },
  {
    id: "p10",
    name: "Linen Dream Cushion",
    brand: "Nestwell",
    pet: "dog",
    category: "Home",
    price: 4480,
    unit: "Medium — 80×60cm",
    rating: 4.9,
    reviews: 206,
    tags: ["Orthopaedic", "Linen", "Removable cover"],
    blurb: "Memory foam under a washed-linen cover. It is, in fact, a very good bed.",
    ingredients: ["Memory foam core", "Washed linen shell", "Recycled fibre fill"],
    tint: "#CFE3D8",
    shape: "bed",
  },
  {
    id: "p11",
    name: "Goat Milk Gelato",
    brand: "Pawpantry",
    pet: "dog",
    category: "Treats",
    price: 420,
    unit: "4 × 100ml",
    rating: 4.7,
    reviews: 528,
    tags: ["Frozen", "Summer", "Probiotic"],
    blurb: "A frozen treat for warmer days. Made with raw goat milk and honey.",
    ingredients: ["Goat milk 82%", "Honey", "Banana", "Live cultures"],
    tint: "#E8DCD5",
    shape: "tub",
  },
  {
    id: "p12",
    name: "Pheasant & Quinoa Dinner",
    brand: "Kinderbowl",
    pet: "dog",
    category: "Wet food",
    price: 1340,
    unit: "12 × 150g trays",
    rating: 4.8,
    reviews: 611,
    tags: ["Single protein", "Novel protein", "Hypoallergenic"],
    blurb: "A novel-protein dinner for sensitive pups. No chicken, no beef, no fuss.",
    ingredients: ["Pheasant 68%", "Quinoa", "Spinach", "Blueberry"],
    tint: "#CFE3D8",
    shape: "tray",
  },
];

export const testimonials: Testimonial[] = [
  {
    quote:
      "Biscuit has never finished her bowl so consistently. Six months in and her coat is genuinely glossier.",
    who: "Ama & Biscuit",
    pet: "Labrador, 4",
  },
  {
    quote: "The calming chews are the only reason we survived bonfire night.",
    who: "Tomas & Luna",
    pet: "Whippet, 2",
  },
];

/** IDs curated to float in the home hero — keeps that layout deterministic. */
export const heroFeaturedIds = ["p1", "p3", "p5"];

export function getProduct(id: string): Product | undefined {
  return products.find((p) => p.id === id);
}

export function getRelated(id: string, n = 4): Product[] {
  const base = getProduct(id);
  if (!base) return products.slice(0, n);
  return products.filter((p) => p.id !== id && p.pet === base.pet).slice(0, n);
}
